docs(docs): update docs for deploy with docker
cubefs/cubefs pull request #1670
Opened 2023-02-15 08:09 UTC by JasonHu520

2023-02-15 08:28 UTC, xiaochunhe approved these changes

2023-02-15 09:13 UTC, xiangcai1215 approved these changes

2023-02-15 09:13 UTC, xiangcai1215 commented on docs/source/user-guide/blobstore.rst
> +    $> docker run cubefs/cubefs:blobstore-v3.2.0 # tun
tun-》run

2023-02-15 16:24 UTC, sejust requested changes

2023-02-15 16:24 UTC, sejust commented on docs-zh/source/user-guide/blobstore.rst
> +blobstore支持docker镜像部署，提供两种方式：
这里提供两种方式。下边又是 1 2 3点，好像不太合适。
把 cli 做成和docker 安装平行的标签

2023-02-15 16:24 UTC, sejust commented on docs-zh/source/user-guide/blobstore.rst
> +   小提示: 进入容器后，可以配置cli，能够更方便地使用
可以简单说一句， cli 是交互式命令行。 用help 可以查看帮助。

2023-02-15 16:24 UTC, sejust commented on docs-zh/source/user-guide/blobstore.rst
> +   $> ./bin/cli -c conf/cli.config
这里应该是  cli.conf ?

2023-02-16 06:55 UTC, sejust submitted a review, later dismissed

2023-02-16 16:13 UTC, sejust approved these changes

2023-02-17 07:57 UTC, xiangcai1215 approved these changes

2023-02-17 09:45 UTC, leonrayang approved these changes

2023-02-17 09:46 UTC, merged