feat(blobstore): add dump snapshot tool for clustermgr of blobstore at cli
cubefs/cubefs pull request #1834
Opened 2023-03-21 03:17 UTC by JasonHu520

2023-03-21 04:21 UTC, sejust requested changes

2023-03-21 04:21 UTC, sejust commented on blobstore/cli/clustermgr/backup.go
> +	_, ctx := trace.StartSpanFromContext(context.Background(), "")
common.CmdContext

2023-03-21 04:21 UTC, sejust commented on blobstore/cli/clustermgr/backup.go
> +	days := c.Args.Int("t")
定义的是  d

2023-03-21 04:21 UTC, sejust commented on blobstore/cli/clustermgr/backup.go
> +	"fmt"
用 cli  common 下的 fmt函数

2023-03-21 04:21 UTC, sejust commented on blobstore/cli/clustermgr/backup.go
> +func decodeSnapshotData(reader io.Reader) (ret *SnapshotData, err error) {
这些编解码在什么地方 有没有统一定义？

2023-03-21 06:31 UTC, JasonHu520 commented on blobstore/cli/clustermgr/backup.go
> +func decodeSnapshotData(reader io.Reader) (ret *SnapshotData, err error) {
这个编码在cm的snapshot吧

2023-03-21 06:31 UTC, JasonHu520 commented on blobstore/cli/clustermgr/backup.go
> +func decodeSnapshotData(reader io.Reader) (ret *SnapshotData, err error) {
> 这些编解码在什么地方 有没有统一定义？

这个编码在cm的snapshot吧

2023-03-21 10:05 UTC, sejust approved these changes

2023-03-22 01:47 UTC, sejust submitted a review, later dismissed

2023-03-22 03:31 UTC, xiangcai1215 approved these changes

2023-03-22 07:29 UTC, merged