[Enhancement] GetCurrentTimeUnix use atomic
cubefs/cubefs pull request #1952
Opened 2023-05-06 06:38 UTC by sjp00556

**What this PR does / why we need it**:
GetCurrentTimeUnix use atomic is much quicker

**benchmark**
```
$ go test -bench="^BenchmarkGet" -run=none
goos: linux
goarch: amd64
pkg: github.com/cubefs/cubefs/metanode
cpu: Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
BenchmarkGetCurrentTimeUnix-16    	1000000000	         0.3317 ns/op
BenchmarkGetCurrentTime-16        	100000000	        10.98 ns/op
BenchmarkGetNowTime-16            	43397809	        27.76 ns/op
PASS
ok  	github.com/cubefs/cubefs/metanode	2.796s
```

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-05-09 06:30 UTC, sejust requested changes

2023-05-09 06:30 UTC, sejust commented on metanode/time_test.go
> +package metanode
Add the "License" into head of the file.

2023-05-09 06:49 UTC, sjp00556 commented
> @sjp00556 Hello, you improve benchmark by adding new a function. It's great, but not the better way in this case.
> 
> 1. without changing the effect of the original function，change `sync.RWMutex` to `atomic.Value`.
> 2. changing return type of function `GetCurrentTime`, just store unix timestamp into `NowTime`.

@sejust maybe some situations need time.Time usage like this: Now.GetCurrentTime().UnixMilli() in future, so i kept GetCurrentTime func and add GetCurrentTimeUnix func which is only to get time unix.

2023-05-09 07:13 UTC, sejust commented
> 1. atomic.Value



> 1. without changing the effect of the original function，change `sync.RWMutex` to `atomic.Value`



> > @sjp00556 Hello, you improve benchmark by adding new a function. It's great, but not the better way in this case.
> > 
> > 1. without changing the effect of the original function，change `sync.RWMutex` to `atomic.Value`.
> > 2. changing return type of function `GetCurrentTime`, just store unix timestamp into `NowTime`.
> 
> @sejust maybe some situations need time.Time usage like this: Now.GetCurrentTime().UnixMilli() in future, so i kept GetCurrentTime func and add GetCurrentTimeUnix func which is only to get time unix and for benchmark purpose

ok，store `now(time.Time)` into atomic.Value without adding a new function.

2023-05-17 06:29 UTC, leonrayang approved these changes

2023-05-17 07:25 UTC, leonrayang approved these changes

2023-05-17 07:26 UTC, merged