fix: remove deprecated ioutil
cubefs/cubefs pull request #2130
Opened 2023-06-12 04:18 UTC by fengshunli

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-06-12 08:26 UTC, sejust commented
@fengshunli  It is recommended that you do not modify the files under the directory `depends/`. This are third-party library that needs to be updated according to they own version.
And Do not format comments that are not related to this submission.Code formatting can be mentioned another PR. Thanks.

2023-06-12 08:28 UTC, sejust commented
Add  `Signed-off-by` in commit. See more at #1920

2023-06-12 08:51 UTC, fengshunli commented
> Add `Signed-off-by` in commit. See more at #1920

done

2023-06-12 10:56 UTC, sejust commented
fix the gofmt https://github.com/cubefs/cubefs/actions/runs/5242644622/jobs/9466305258?pr=2130

2023-06-12 11:13 UTC, fengshunli commented
> fix the gofmt https://github.com/cubefs/cubefs/actions/runs/5242644622/jobs/9466305258?pr=2130

merge

2023-06-12 11:45 UTC, sejust requested changes

2023-06-12 11:45 UTC, sejust commented on blobstore/blobnode/core/disk/trash.go
> +		info, _ := fi.Info()
the returned error cannot be ignored

2023-06-12 11:45 UTC, sejust commented on metanode/util.go
> +			fileInfo, _ := info.Info()
the error cannot be ignored.

2023-06-13 08:14 UTC, fengshunli commented on metanode/util.go
> +			fileInfo, _ := info.Info()
done

2023-06-13 08:14 UTC, fengshunli commented on blobstore/blobnode/core/disk/trash.go
> +		info, _ := fi.Info()
done

2023-06-13 08:41 UTC, sejust approved these changes

2023-06-13 08:44 UTC, fengshunli commented on blobstore/blobnode/base/util_test.go
> +//	"Range": "bytes=150-"
Commonly used indentation, here is two spaces

2023-06-13 08:44 UTC, fengshunli commented on blockcache/bcache/manage.go
> +//		return nil
done

2023-06-13 08:52 UTC, sejust commented on blobstore/blobnode/base/util_test.go
> +//	"Range": "bytes=150-"
https://tip.golang.org/doc/comment

2023-06-13 08:56 UTC, fengshunli commented on blobstore/blobnode/base/util_test.go
> +//	"Range": "bytes=150-"
<img width="411" alt="image" src="https://github.com/cubefs/cubefs/assets/18587688/4ed3a11a-6b76-412b-96fc-fb8df49b7d51">
The format in the document is the same as my current submission

2023-06-13 09:09 UTC, sejust approved these changes

2023-06-14 11:46 UTC, leonrayang commented
@fengshunli need combine the commits to several import one

2023-06-14 11:48 UTC, leonrayang commented
@fengshunli the commits include some one not belong to you，need push the commits again.

2023-06-14 11:55 UTC, fengshunli commented
> @fengshunli the commits include some one not belong to you，need push the commits again.

@leonrayang switch a branch push

2023-06-14 12:21 UTC, closed without merging