fix(rpc): a custom readCloser is used as request.body to count the size of…
cubefs/cubefs pull request #2247
Opened 2023-07-06 07:02 UTC by shuqiang-zheng

fix(rpc): a custom readCloser is used as request.body to count the size of the request body

in previous version,blobstore access upload no metric if there is no context-length in the request header,now the size is counted when read request body

Fixes #2120

2023-07-06 09:02 UTC, sejust requested changes

2023-07-06 09:20 UTC, sejust requested changes

2023-07-06 09:20 UTC, sejust commented on blobstore/common/rpc/auditlog/auditlog.go
> +	return reqBody.Close()
SA5007: infinite recursive call

2023-07-07 01:41 UTC, sejust requested changes

2023-07-07 01:41 UTC, sejust commented on blobstore/common/rpc/auditlog/auditlog_test.go
> +func initNoContextLengthServer(t *testing.T) (server *httptest.Server, tmpDir string, lc LogCloser) {
rename all  `ContextLength` to content length.

2023-07-07 02:10 UTC, sejust approved these changes

2023-07-07 02:19 UTC, Cloudstriff approved these changes
LGTM

2023-07-07 02:28 UTC, merged