chore: os.SEEK_CUR os.SEEK_END os.SEEK_SET has been deprecated
cubefs/cubefs pull request #2384
Opened 2023-08-01 09:46 UTC by testwill

**What this PR does / why we need it**:
remove os.SEEK_CUR os.SEEK_END os.SEEK_SET
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

2023-08-21 01:36 UTC, xiangcai1215 approved these changes
LGTM

2023-08-21 01:57 UTC, cessory submitted a review, later dismissed

2023-08-21 02:35 UTC, cessory commented
go format check error

2023-08-21 02:42 UTC, sejust requested changes

2023-08-21 02:42 UTC, sejust commented on util/log/log_get.go
> +	"io"
fix import's order with `gofmt -l -w log_get.go`

2023-08-22 01:36 UTC, cessory approved these changes

2023-08-22 02:53 UTC, sejust approved these changes

2023-08-22 03:33 UTC, merged