feat(master/data/cli): master/datanode support datanode's media, and …
cubefs/cubefs pull request #2463
Opened 2023-08-09 09:50 UTC by true1064

**What this PR does / why we need it**:

feat(master/data/cli): master/datanode support datanode's media, and cli datanode info shows datanode's media

2023-08-10 08:04 UTC, baijiaruo approved these changes
LGTM

2023-08-10 10:11 UTC, xiaochunhe requested changes

2023-08-10 10:11 UTC, xiaochunhe commented on master/api_args_parse.go
> +	if value = r.FormValue(mediaTypeKey); value == "" {
if value := r.FormValue(mediaTypeKey); value == "" {
		mediaType = proto.MediaType_Unspecified
		return
	}

2023-08-10 10:12 UTC, xiaochunhe commented on master/topology_test.go
>  	"testing"
"fmt"
	"testing"
	"time"

	"github.com/cubefs/cubefs/util"
	"github.com/cubefs/cubefs/proto"

2023-08-30 02:28 UTC, bboyCH4 approved these changes

2023-08-30 02:37 UTC, baijiaruo approved these changes
LGTM

2023-08-30 02:37 UTC, merged