feat(rpc): #1924 add log filter
cubefs/cubefs pull request #2591
Opened 2023-09-05 05:58 UTC by 123456951

**What this PR does / why we need it**:

**Which issue this PR fixes**:

feat(rpc): #1924 add log filter

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-09-05 08:13 UTC, sejust commented
@123456951 fix under directory `./blobstore/common/rpc/auditlog`

1. code formats with 'gofumpt' at version v0.2.1
install with command: `go install mvdan.cc/gofumpt@v0.2.1`
then:  `gofumpt -l -w .`

2. code golangci lint with 'golangci-lint' version v1.43.0
install with command: `go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0`
then: `golangci-lint run --issues-exit-code=1 -D errcheck -E bodyclose .`

2023-09-06 02:59 UTC, sejust requested changes

2023-09-06 02:59 UTC, sejust commented on blobstore/common/rpc/auditlog/filter.go
> +//}
配置文件应该分两种类型：
1、逻辑运算：Must、MustNot、Should
2、关系运算：Term、Match、Range、Regexp

第一版本先不考虑嵌套关系，按照如写两层就够就可以：
```
{
  "must": {
      ... 关系运算
   },    
}
```

2023-09-06 02:59 UTC, sejust commented on blobstore/common/rpc/auditlog/filter.go
> +}
Must、MustNot、Should  应该都是一个  func(Log) bool 的handler 。
比如 must 的handler 是：
```
func must(log AuditLog) bool {
        return handleTerm(log) && handleMatch(log) ...
}
```

2023-09-06 02:59 UTC, sejust commented on blobstore/common/rpc/auditlog/filter.go
> +var priorityQueue PriorityQueue
优先级应该作为 filter的一个字段，最好不要用全局变量

2023-09-06 02:59 UTC, sejust commented on blobstore/common/rpc/auditlog/filter.go
> +			case "term":
所有  term 的关系运算都可以抽象成一个函数吧。
`termFunc` 是解析配置的时候生成的。
```
func handleTerm(log AuditLog) bool {
        for _, termFunc := range terms {
                if !termFunc(log) {
                        return false
                }
        }
        return true
}
```

2023-09-06 02:59 UTC, sejust commented on blobstore/common/rpc/auditlog/filter.go
> +func logFieldValue(log AuditLog, field string) interface{} {
在解析阶段就应该把配置求值，以下是一个简单的例子：
```
func parse(operation, field, value string) (func(log AuditLog) bool, error) {
        err := fmt.Errorf("unsupported (%s %s)", field, operation)

        switch field {
        case "module":
                switch operation {
                case "term":
                        return func(log AuditLog) bool {
                                return log.Module == value
                        }, nil
                case "match":
                        return func(log AuditLog) bool {
                                return strings.Contains(log.Module, value)
                        }, nil
                case "regexp":
                default:
                        return nil, err
                }
        case "start_time":
                switch operation {
                case "range":
                        gte, e := strconv.ParseInt(value, 10, 64)
                        if e != nil {
                                return nil, e
                        }
                        return func(log AuditLog) bool {
                                return log.StartTime > int64(gte)
                        }, nil
                default:
                        return nil, err
                }
        default:
        }
        return nil, err
}

```

2023-09-06 02:59 UTC, sejust commented on blobstore/common/rpc/auditlog/filter_test.go
> +func TestFilter(t *testing.T) {
可以分多个测试用例， 尽量保证代码覆盖率到 90% 以上

2023-09-14 09:02 UTC, sejust requested changes

2023-09-28 01:15 UTC, 123456951 commented on blobstore/common/rpc/auditlog/filter.go
> +			return nil, err
已更新

2023-09-28 01:19 UTC, 123456951 commented on blobstore/common/rpc/auditlog/filter.go
> +			switch key {
按原先的结构已经实现range解析了

2023-10-10 08:32 UTC, sejust requested changes

2023-10-10 08:32 UTC, sejust approved these changes

2023-10-10 08:34 UTC, merged

2024-01-26 05:00 UTC, sejust commented
Merged into master [3b98c0233](https://github.com/cubefs/cubefs/commit/3b98c02332ba1d3795f310b97bb2a5e9fb1dc157)