feat(blobstore): to support objectnode auditlog
cubefs/cubefs pull request #2632
Opened 2023-09-21 06:09 UTC by yhjiango

**What this PR does / why we need it**:
In order to support the audit log of objectnode, certain modifications need to be made to the audit log of blobstore. For example:
1. Additional information needs to be printed in the audit log, but these fields cannot be passed to the user.
2. For the successful response of 2xx, it is completely unnecessary to print the data read by the user. Here, add a configuration item to disable body printing.
3. Fix the problem that the original context cannot be assigned by kv.

**Which issue this PR fixes**:

fixes #

2023-09-21 10:21 UTC, sejust commented
补一下测试用例。

2023-09-21 10:22 UTC, sejust requested changes

2023-09-21 10:22 UTC, sejust commented on blobstore/common/rpc/auditlog/proto.go
> +}
新加接口、特性尽量使用语言内置类型
```
type ResponseServerHeader interface {
        ServerHeader() http.Header
}
```

2023-09-21 10:22 UTC, sejust commented on blobstore/common/rpc/auditlog/response.go
> +		} else if k == "ETag" && len(header[k]) > 0 {
这里是什么情况下需要这样用？

2023-09-21 10:22 UTC, sejust commented on blobstore/common/rpc/auditlog/response.go
> +	for h, v := range w.extra {
如果 extra header 和  原始 header k 冲突的话，应该保留返回到客户端的值？

2023-09-25 02:31 UTC, sejust submitted a review, later dismissed

2023-09-25 06:05 UTC, sejust approved these changes

2023-09-25 06:14 UTC, xiangcai1215 approved these changes
LGTM

2023-09-25 06:17 UTC, merged