[Feature]: Backend audit log support configure in master
cubefs/cubefs pull request #2728
Opened 2023-10-31 09:16 UTC by NaturalSelect

**What this PR does / why we need it**:

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-11-02 02:07 UTC, Victor1319 approved these changes
LGTM

2023-11-02 03:23 UTC, bboyCH4 approved these changes

2023-11-02 03:26 UTC, bboyCH4 requested changes
please combine these commits to one

2023-11-02 03:27 UTC, NaturalSelect commented
> please combine these commits to one

OK

2023-11-03 06:11 UTC, bboyCH4 approved these changes

2023-11-09 07:10 UTC, merged