volume allocation optimization
cubefs/cubefs pull request #2798
Opened 2023-11-22 12:01 UTC by tangdeyi

The idle volume is stored in shards to reduce the lock scope.

2023-11-23 03:27 UTC, mawei029 commented on blobstore/clustermgr/volumemgr/alloc.go
> +	allocatable *list.List
这个Shard结构体，是否可以不用再多包一层，直接放到idleVolumes里使用？

2023-11-23 03:27 UTC, mawei029 commented on blobstore/clustermgr/volumemgr/alloc.go
> +GetOneShardAgain:
这个函数逻辑变化，是否可以加个ut？

2023-11-23 03:30 UTC, mawei029 commented on blobstore/clustermgr/volumemgr/alloc.go
>  RETRY:
这里好改不，goto语句一般从规范上来讲，不建议往回跳。改成往后跳，或者用for,匿名函数等其它方式替换

2023-11-24 03:15 UTC, sejust requested changes

2023-11-24 03:15 UTC, sejust commented on blobstore/clustermgr/volumemgr/alloc.go
> +	return int(atomic.LoadInt64(&i.allAllocatableNum))
这里不需要锁，

2023-11-24 03:15 UTC, sejust commented on blobstore/clustermgr/volumemgr/alloc.go
> +	rand.Seed(time.Now().UnixNano())
seed 设置一次就够了

2023-11-24 03:41 UTC, sejust approved these changes

2023-11-24 08:32 UTC, JasonHu520 approved these changes

2023-11-29 07:29 UTC, merged