some feature/bugfix from blobstore v1.2.4 (optimize data inspect, reports the I/O dequeue time)
cubefs/cubefs pull request #2812
Opened 2023-11-27 11:39 UTC by mawei029

**What this PR does / why we need it**:

1. support the inpect switch can be set from clustermgr(unified interface), set inspect rate limit from http
2. skip init new disk storage, when the disk is broken
3. io pool add prometheus, It reports the dequeue time of each I/O

**Which issue this PR fixes**:

fixes #2767 
fixes #2768
fixes #2779 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-11-29 08:23 UTC, sejust requested changes

2023-11-29 08:23 UTC, sejust commented on blobstore/util/taskpool/iopool.go
> +	case <-p.closed:
这里 return 前 需要执行下 `args.TaskFn()`  不然这个 task 就丢了。

2023-11-29 08:23 UTC, sejust commented on blobstore/util/taskpool/iopool.go
> +	p.queue[idx] <- task
如果 在closed 发生前 这个task 在等待入队； 再发生了Close，同样会panic 。

2023-11-29 08:23 UTC, sejust commented on blobstore/util/taskpool/iopool.go
> +	"github.com/cubefs/cubefs/blobstore/common/proto"
util 库不可以 import common ， 不然可能出现循环引用。  把iopool 放到common里

2023-11-29 08:23 UTC, sejust commented on blobstore/util/taskpool/iopool.go
> +			Subsystem:  "blobnode",
基础库还有这种硬编码不太合理， 可以通过conf传过来

2023-11-29 13:22 UTC, mawei029 commented on blobstore/util/taskpool/iopool.go
> +	"github.com/cubefs/cubefs/blobstore/common/proto"
去掉引用common了

2023-11-30 03:01 UTC, sejust approved these changes

2023-12-01 07:16 UTC, tangdeyi approved these changes
LGTM

2023-12-01 07:19 UTC, merged