ClusterMgr supports sealed status and provides some new client interfaces
cubefs/cubefs pull request #2823
Opened 2023-11-29 09:10 UTC by tangdeyi

1. add cache interface and alloc volume v2
2. add volume release interface
3. add a new status sealed for volume
4. add interface to set volume idle for clusterMgr

2023-11-29 11:48 UTC, JasonHu520 commented on blobstore/clustermgr/volumemgr/alloc.go
> +			if allocatableSize == a.allocatableSize {
这个判断应该不需要

2023-11-30 03:35 UTC, tangdeyi commented on blobstore/clustermgr/volumemgr/alloc.go
> +			if allocatableSize == a.allocatableSize {
这个判断是为了兼容needSize等于0的场景，是需要的

2023-11-30 11:02 UTC, sejust requested changes

2023-11-30 11:09 UTC, tangdeyi commented on blobstore/api/clustermgr/cacher.go
> +	return disk, nil
已改

2023-11-30 11:14 UTC, tangdeyi commented on blobstore/common/proto/const.go
> +	return "unknown"
已改

2023-11-30 11:15 UTC, tangdeyi commented on blobstore/clustermgr/volume.go
> +	if ret != nil {
已改

2023-12-01 02:29 UTC, sejust approved these changes

2023-12-15 08:06 UTC, JasonHu520 approved these changes

2023-12-19 06:11 UTC, merged