remove kafka for scheduler
cubefs/cubefs pull request #2957
Opened 2023-12-29 08:14 UTC by JasonHu520

**What this PR does / why we need it**:
remove the kafka module and adjust the inspection process to support sealed volume operations
**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-12-29 08:53 UTC, sejust requested changes

2023-12-29 08:53 UTC, sejust commented on blobstore/common/proto/proxy.go
> +	return stageMap[d]
改成 siwtch， map 效率较低。

2023-12-29 08:53 UTC, sejust commented on blobstore/scheduler/blob_deleter.go
> +func (mgr *BlobDeleteMgr) Run() {}
函数里加个这个 `_ = struct{}{}`,  有一个空函数检查的代码格式过不了。

2023-12-29 08:53 UTC, sejust commented on blobstore/scheduler/volume_inspector.go
> +	"github.com/cubefs/cubefs/blobstore/common/codemode"
import 整理下

2024-01-02 02:03 UTC, sejust approved these changes

2024-01-02 06:49 UTC, mawei029 commented on blobstore/scheduler/blob_deleter.go
> +	_ = struct{}{}
_ = struct{}{} 这一行是不是可以删掉？

2024-01-02 06:49 UTC, mawei029 commented on blobstore/scheduler/volume_inspector.go
> +//type getIdleToSealedVolArgs struct {
这一大段现在没用了，删掉

2024-01-02 06:58 UTC, sejust commented on blobstore/scheduler/blob_deleter.go
> +	_ = struct{}{}
这是为了代码空函数检查的

2024-01-02 06:58 UTC, mawei029 commented on blobstore/scheduler/shard_repairer.go
>  func (mgr *ShardRepairMgr) Run() {
空的Run函数和blob_deleter.go保持一致。加 _ = struct{}{}，标明注释 for code check

2024-01-02 07:16 UTC, mawei029 approved these changes

2024-01-02 07:47 UTC, tangdeyi approved these changes

2024-01-02 08:07 UTC, merged