[Chore]: Build in docker support go build cache
cubefs/cubefs pull request #2995
Opened 2024-01-14 09:37 UTC by NaturalSelect

**What this PR does / why we need it**:

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-01-15 02:47 UTC, sejust requested changes

2024-01-15 02:47 UTC, sejust commented on docker/run_docker.sh
> +compose="docker-compose --env-file ${RootPath}/docker/run_docker.env  -f ${RootPath}/docker/docker-compose.yml"
这一行没必要改吧

2024-01-15 02:47 UTC, sejust commented on docker/run_docker.sh
> +    ${compose} run --rm --volume "$(get_go_build_cache):/root/.cache/go-build" build
--rm 参数很好， 很多 run 命令都需要加上；如 `run_unit_test` `run_format` `run_build_libsdkpre` `run_goreleaser` `run_bsgofumpt` `run_bsgolint` `run_gosec` `build` `build_s3。
 
 --volume 参数可以做出可选项， 如果  ./run_docker.sh  有 --gocache 参数就启用 go-build 卷，不是所有人都需要，而且在workflow 中 每次都没有cache。

2024-01-15 02:51 UTC, sejust commented on docker/run_docker.sh
> +    ${compose} run --rm --volume "$(get_go_build_cache):/root/.cache/go-build" build
或者再设置一个 env ，  需要的人 不用每次都加 -- 相关参数

2024-01-15 08:59 UTC, NaturalSelect commented on docker/run_docker.sh
> +    ${compose} run --rm --volume "$(get_go_build_cache):/root/.cache/go-build" build
> 或者再设置一个 env ， 需要的人 不用每次都加 -- 相关参数

When the host has installed GO, it will automatically enable build cache.

2024-01-23 07:15 UTC, leonrayang approved these changes
LGTM

2024-01-23 07:15 UTC, merged