feat(master): compress client/partitions response data
cubefs/cubefs pull request #3021
Opened 2024-01-22 07:11 UTC by lily-lee

**What this PR does / why we need it**:

compress client/partitions response data

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-02-02 08:49 UTC, sejust commented
compress 是不是可以在很多接口上应用？ 可以再进一步设计个比较通用的使用方式

2024-02-02 08:50 UTC, sejust commented on util/compressor/gzip_compressor.go
> +func (c *gzipCompressor) Compress(b []byte) ([]byte, error) {
`gzipCompressor` 这个结构是多余的，  `Compress` `Decompress` 可以直接是函数。

2024-02-02 08:50 UTC, sejust commented on util/compressor/gzip_compressor.go
> +func NewGzipCompressor() *gzipCompressor {
如果要使用一个通用的模板，这里最好返回一个 interface
```
Compressor insterface {
Blabla
}
```
`gzipCompressor`
`zlibCompressor`
......

2024-02-02 08:50 UTC, sejust commented on util/compressor/gzip_compressor.go
> +	buf := new(bytes.Buffer)
bytes.Buffer  也可以复用

2024-02-02 08:50 UTC, sejust commented on sdk/master/client.go
> +		if r.params["compress"] == "true" && resp.StatusCode == http.StatusOK {
这里最好写到 下边 `case http.StatusOK`里比较清晰

2024-02-02 08:50 UTC, sejust commented on sdk/master/api_client.go
> +func (api *ClientAPI) GetDataPartitionsCompress(volName string, compress bool) (view *proto.DataPartitionsView, err error) {
新增函数和 `GetDataPartitions` 完全重复了， `GetDataPartitions` == `GetDataPartitionsCompress("xxx", false)`

2024-02-02 10:52 UTC, lily-lee commented on util/compressor/gzip_compressor.go
> +func (c *gzipCompressor) Compress(b []byte) ([]byte, error) {
改成这样可以吗？
```go
type Compressor interface {
	Name() string
	Compress([]byte) ([]byte, error)
	Decompress([]byte) ([]byte, error)
}

var GzipCompressor = NewGzipCompressor()

func NewGzipCompressor() *gzipCompressor {
	return &gzipCompressor{buf: new(bytes.Buffer)}
}

type gzipCompressor struct {
	buf *bytes.Buffer
}

func (c *gzipCompressor) Compress(b []byte) ([]byte, error) {
	defer c.buf.Reset()
	gw := gzip.NewWriter(c.buf)
	if _, err := gw.Write(b); err != nil {
		return nil, err
	}
	if err := gw.Close(); err != nil {
		return nil, err
	}
	return c.buf.Bytes(), nil
}
```

2024-02-02 10:55 UTC, sejust commented on util/compressor/gzip_compressor.go
> +func (c *gzipCompressor) Compress(b []byte) ([]byte, error) {
这样不能并发。

2024-02-06 06:44 UTC, sejust approved these changes

2024-02-06 06:44 UTC, sejust commented on master/api_service.go
> +		body, err = compressor.New(r.Header.Get(proto.HeaderAcceptEncoding)).Compress(body)
这行应该放到 `if compress {` 里？

2024-02-06 06:44 UTC, sejust commented on master/api_service.go
> +		w.Header().Add(proto.HeaderContentEncoding, compressor.EncodingGzip)
这行代码需要放到 `send(w, r, body)` 前。比如 err != nil，返回压缩，客户端可能解不出来

2024-02-06 06:44 UTC, sejust commented on master/const.go
> +	compressKey                = "compress"
这行应该是忘记删了吧

2024-02-06 06:56 UTC, sejust requested changes

2024-02-06 06:56 UTC, sejust commented on master/data_partition_map.go
> +		dpResps := dpMap.getDataPartitionsView(minPartitionID)
这些代码和`updateResponseCache` 重复了。 
这里 如果 compress 没有，就直接调用 `updateResponseCache` 获取 原始 bytes，再压缩存储。

2024-02-06 09:19 UTC, sejust approved these changes

2024-02-18 01:42 UTC, sejust submitted a review, later dismissed

2024-02-23 08:35 UTC, sejust approved these changes

2024-02-27 02:12 UTC, leonrayang approved these changes
LGTM

2024-02-27 02:29 UTC, sejust approved these changes

2024-02-27 02:30 UTC, merged