feat(access): delete blob msg, remove proxy kafka delete and repair msg
cubefs/cubefs pull request #3050
Opened 2024-01-29 09:00 UTC by mawei029

**What this PR does / why we need it**:
 delete blob msg, remove proxy kafka delete and repair msg
**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-01-29 09:19 UTC, sejust requested changes

2024-01-29 09:19 UTC, sejust commented on blobstore/access/stream_put.go
>  		for idx := range volume.Units {
这段代码也没用了

2024-01-29 09:19 UTC, sejust commented on blobstore/access/stream.go
> +					err = h.blobnodeClient.DeleteShard(ctx, host, &args)
删除失败怎么办？

2024-01-29 09:19 UTC, sejust commented on blobstore/access/stream.go
>  	deleteArgs := &proxy.DeleteArgs{
这个也没用了

2024-01-29 09:27 UTC, mawei029 commented on blobstore/access/stream_put.go
>  		for idx := range volume.Units {
这里面留给另一个MR，写流程那边 统计累加quorum需要
https://github.com/cubefs/cubefs/pull/2972/files#diff-18e939828a06290b0eb240d2161e262481c50b9904df8175afab4cf9123eea4a

2024-01-29 09:27 UTC, mawei029 commented on blobstore/access/stream.go
> +					err = h.blobnodeClient.DeleteShard(ctx, host, &args)
删除失败不处理，留给scheduler后台巡检

2024-01-30 06:26 UTC, JasonHu520 approved these changes

2024-01-30 06:41 UTC, mawei029 commented on blobstore/access/stream.go
> +					err = h.blobnodeClient.DeleteShard(ctx, host, &args)
修改为删除需要多数派成功，删除失败的会做一些重试

2024-01-30 10:13 UTC, cessory approved these changes

2024-01-30 10:13 UTC, merged