feat(access): one client is bound to one cluster
cubefs/cubefs pull request #3085
Opened 2024-02-07 09:05 UTC by mawei029

**What this PR does / why we need it**:

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-02-18 02:01 UTC, sejust requested changes

2024-02-18 02:01 UTC, sejust commented on blobstore/access/stream_put.go
> +		_, ok := h.failVids.Load(vid)
LoadOrStore

2024-02-19 02:09 UTC, JasonHu520 commented on blobstore/access/stream_put.go
> +type failVuidMap struct {
可以直接用sync.Map，计数就用原子操作就可以？

2024-02-19 02:13 UTC, mawei029 commented on blobstore/access/stream_put.go
> +type failVuidMap struct {
这里的结构体是在395行的sync.Map里value用的，sync.Map不能嵌套

2024-02-19 02:19 UTC, sejust approved these changes

2024-02-19 02:52 UTC, mawei029 commented on blobstore/access/stream_put.go
> +		_, ok := h.failVids.Load(vid)
ok

2024-02-19 02:53 UTC, mawei029 commented on blobstore/access/stream_put.go
> +type failVuidMap struct {
ok

2024-02-19 03:00 UTC, JasonHu520 approved these changes

2024-02-19 03:01 UTC, merged