minor code and comment refactoring
cubefs/cubefs pull request #3096
Opened 2024-02-19 06:31 UTC by yj-yoo

**What this PR does / why we need it**:

- remove redundant 'return' state
- simplify conditional expressions
- remove ineffectual assignment
 - 'fdstore.go, line 280' It will not be referenced again in the 'for' loop it belongs to, and will then be overwritten with a new value in the 'os.OpenFile()' function.
 - 'fdstore.go, line 303' Handling of the 'fmt.Errorf()' function ends without processing
 - 'io.gok line 114' slice is initialized automatically, and since it is not a pointer, it does not use nil.
 - 'flag.go, line 740' This could directly return the return value of 'fmt.Errorf()' (actually it doesn't seem necessary, but I can't figure out the intent, so it preserves the meaning of the code)
 - 'serve.go, line 1840' It is continuously initialized within the for loop and will not be referenced beyond the line in use.
- fix replaceable functions
- fix return that doesn't reach
- fix typo
- edit comments

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-02-19 07:04 UTC, sejust requested changes

2024-02-19 07:04 UTC, sejust commented on fdstore/fdstore.go
> +		fmt.Errorf("failed to open handles list file: %v\n", err)
fmt.Fprintf ??

2024-02-19 07:11 UTC, yj-yoo commented on fdstore/fdstore.go
> +		fmt.Errorf("failed to open handles list file: %v\n", err)
ok. I applied it. thanks

2024-02-19 07:14 UTC, sejust approved these changes

2024-02-29 06:33 UTC, leonrayang approved these changes
LGTM

2024-02-29 06:43 UTC, merged