feat(access): support sdk, merge blobstore access into cubefs sdk
cubefs/cubefs pull request #3263
Opened 2024-03-14 08:55 UTC by mawei029

**What this PR does / why we need it**:
support sdk, merge blobstore access into cubefs sdk

**Which issue this PR fixes**:

fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-03-15 09:40 UTC, sejust requested changes

2024-03-15 09:40 UTC, sejust commented on blobstore/access/sdk/sdk_client.go
> +	return ioutil.NopCloser(bytes.NewReader(buf)), nil
io.NopCloser

2024-03-15 09:40 UTC, sejust commented on blobstore/access/sdk/sdk_client.go
> +	buf := make([]byte, args.ReadSize)
using stream

2024-03-25 08:55 UTC, JasonHu520 commented on blobstore/access/sdk/sdk_client.go
> +			BlobSize:  1,
这个是不是可以干掉，0和1没区别似乎

2024-03-25 09:07 UTC, JasonHu520 commented on blobstore/access/sdk/sdk_client.go
> +		if loc.Size > 0 {
如果前面初始化为1，这里就不用判断咯

2024-03-25 09:07 UTC, JasonHu520 commented on blobstore/access/stream_mock_test.go
> +//go:generate mockgen -destination=../testing/mocks/access_stream.go -package=mocks -mock_names StreamHandler=MockStreamHandler github.com/cubefs/cubefs/blobstore/access StreamHandler
目标文件可以加个mock前缀

2024-03-26 06:28 UTC, sejust commented on blobstore/access/stream_mock_test.go
> +//go:generate mockgen -destination=../testing/mocks/access_stream.go -package=mocks -mock_names StreamHandler=MockStreamHandler github.com/cubefs/cubefs/blobstore/access StreamHandler
放到testing目录下的不用加，重复了

2024-04-02 02:00 UTC, closed without merging