Enhancement: refactor exporter metrics collector to multi-backends and implement prometheus and opentsdb backends
cubefs/cubefs pull request #598
Opened 2020-05-29 06:04 UTC by ZhuZhengyi

Signed-off-by: zhuzhengyi1 <zhuzhengyi@jd.com>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2020-06-03 02:12 UTC, mervinkid requested changes

2020-06-03 02:12 UTC, mervinkid commented on util/exporter/opentsdb_backend.go
> +	DataPointsPostMaxSize = 50        //一次最多发送datapoint个数
Unify notes into English.

2020-06-03 02:20 UTC, ZhuZhengyi commented on util/exporter/opentsdb_backend.go
> +	DataPointsPostMaxSize = 50        //一次最多发送datapoint个数
done

2020-06-03 10:56 UTC, awzhgw approved these changes
review+1

2020-06-03 10:56 UTC, awzhgw commented
@ZhuZhengyi  we will merge it to new version

2020-06-12 04:43 UTC, mervinkid approved these changes

2026-06-09 01:59 UTC, leonrayang commented
@ZhuZhengyi 
Thank you for this contribution.

This branch is quite old and has not been kept up to date with the current default branch. There is a large divergence from today’s master, and bringing this patch forward would require a substantial rebase or rewrite rather than a simple merge.

For these reasons, we are closing this PR for now. If you’re still interested and the change remains relevant, you’re welcome to rebase onto the latest master or open a fresh PR — we’d be happy to take another look.

2026-06-09 01:59 UTC, closed without merging